# Generated by Django 3.0 on 2019-12-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortURL",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),

                ),
                (
                    "shortened_id",
                    models.CharField(editable=False, max_length=8, unique=True),
                ),
                ("path", models.CharField(editable=False, max_length=100)),
            ],
        ),
    ]
