# Generated by Django 3.0 on 2019-12-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortened_id', models.CharField(editable=False, max_length=8, unique=True)),
                ('path', models.CharField(editable=False, max_length=100)),
            ],
        ),
    ]
