# Generated by Django 6.0.3 on 2026-03-23 19:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shorturl',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='shorturl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='redirect_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='path',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['shortened_id'], name='shortener_s_shorten_202db6_idx'),
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['created_at'], name='shortener_s_created_368a5c_idx'),
        ),
    ]
