# Generated by Django 4.2.20 on 2026-07-18 03:29

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
import djrichtextfield.models
import uuid


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# groups.migrations.0007_populate_uuid_values_groupmember

class Migration(migrations.Migration):

    replaces = [('groups', '0001_initial'), ('groups', '0002_auto_20191213_0829'), ('groups', '0003_auto_20191218_1122'), ('groups', '0004_auto_20191222_1104'), ('groups', '0005_auto_20191222_1237'), ('groups', '0006_groupmember_member_id'), ('groups', '0007_populate_uuid_values_groupmember'), ('groups', '0008_remove_uuid_null'), ('groups', '0009_groupmember_is_deleted'), ('groups', '0010_auto_20201016_1046'), ('groups', '0011_auto_20201019_1243'), ('groups', '0012_groupmessageimage'), ('groups', '0013_groupmemberrsvp'), ('groups', '0014_auto_20260323_1830'), ('groups', '0015_alter_group_options_alter_groupmember_options_and_more'), ('groups', '0016_auto_20260323_1943'), ('groups', '0017_remove_group_temp_id_alter_group_created_at_and_more'), ('groups', '0018_groupschedule_instructions_and_more'), ('groups', '0019_alter_groupmessage_options_and_more'), ('groups', '0020_remove_group_event_date'), ('groups', '0021_groupevent_delete_groupschedule'), ('groups', '0022_alter_groupevent_options_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('message_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('S', 'Successfully Sent'), ('F', 'Sending Failed')], default='P', max_length=1)),
                ('message_type', models.CharField(choices=[('AM', 'Admin to Members'), ('MA', 'Member to Admin')], default='AM', max_length=2)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sent', to=settings.AUTH_USER_MODEL)),
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reply_to', models.UUIDField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('schedule_time', models.DateTimeField()),
                ('instructions', models.TextField(blank=True)),
                ('venue_name', models.CharField(blank=True, max_length=255, null=True)),
                ('venue_address', models.TextField(blank=True)),
                ('venue_map_link', models.CharField(max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('member_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='member_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=djrichtextfield.models.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='groupmember',
            options={'ordering': ['user__first_name']},
        ),
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='groupschedule',
            options={'ordering': ['-rsvp_open']},
        ),
        migrations.RemoveField(
            model_name='group',
            name='group_id',
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('user', 'group')},
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='message',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='message_id',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='message_time',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='groupschedule',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='groupschedule',
            name='schedule_time',
        ),
        migrations.RemoveField(
            model_name='groupschedule',
            name='venue_address',
        ),
        migrations.RemoveField(
            model_name='groupschedule',
            name='venue_map_link',
        ),
        migrations.RemoveField(
            model_name='groupschedule',
            name='venue_name',
        ),
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='body',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='send_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='subject',
            field=models.CharField(default='No Subject', max_length=120),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='groupschedule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='groupschedule',
            name='rsvp_close',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupschedule',
            name='rsvp_open',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='message_type',
            field=models.CharField(choices=[('AM', 'Admin to Members'), ('MA', 'Member to Admin')], max_length=2),
        ),
        migrations.CreateModel(
            name='GroupMessageImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='message_images/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='groups.groupmessage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='groupschedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='groupschedule',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groupschedule',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='GroupInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=17, null=True)),
                ('invite_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expired', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='groups.group')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='member_id',
        ),
        migrations.AddField(
            model_name='group',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunSQL(
            sql="UPDATE groups_group SET temp_id = (SELECT hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(6))) WHERE temp_id IS NULL;",
        ),
        migrations.AddField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='group',
            name='temp_id',
        ),
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='groupinvite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='groupmessageimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='groupschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='groupschedule',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupschedule',
            name='schedule_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupschedule',
            name='venue_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupschedule',
            name='venue_map_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='groupschedule',
            name='venue_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'ordering': ['-message_time']},
        ),
        migrations.RenameField(
            model_name='groupmessage',
            old_name='body',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='groupmessageimage',
            name='message',
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='message_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='groups.groupmessage'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmessageimage',
            name='group_message',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_images', to='groups.groupmessage'),
        ),
        migrations.RemoveField(
            model_name='group',
            name='event_date',
        ),
        migrations.CreateModel(
            name='GroupEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('event_time', models.DateTimeField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('venue_name', models.CharField(blank=True, max_length=255, null=True)),
                ('venue_address', models.TextField(blank=True, null=True)),
                ('venue_map_link', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='groups.group')),
            ],
            options={
                'ordering': ['-event_time'],
            },
        ),
        migrations.DeleteModel(
            name='GroupSchedule',
        ),
    ]
