# Generated by Django 3.0 on 2019-12-18 11:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20191213_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='message_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='reply_to',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
