# Generated by Django 3.0 on 2019-12-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20191222_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupschedule',
            name='venue_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
