# Generated by Django 3.0 on 2020-03-11 08:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0005_auto_20191222_1237"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmember",
            name="member_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
