# Generated by Django 3.0 on 2020-03-11 08:45

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    GroupMember = apps.get_model("groups", "GroupMember")
    for row in GroupMember.objects.all():
        row.member_id = uuid.uuid4()
        row.save(update_fields=["member_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0006_groupmember_member_id"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop)
    ]
