# Generated by Django 3.0 on 2020-03-11 08:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_populate_uuid_values_groupmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='member_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
