# Generated by Django 3.0 on 2020-03-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0008_remove_uuid_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmember",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
