# Generated by Django 2.2.6 on 2020-10-16 10:46

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_groupmember_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=djrichtextfield.models.RichTextField(blank=True),
        ),
    ]
