# Generated by Django 2.2.6 on 2020-10-19 12:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_auto_20201016_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
