# Generated by Django 2.2.6 on 2020-10-27 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_auto_20201019_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMessageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('group_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.GroupMessage')),
            ],
        ),
    ]
