# Generated by Django 2.2.6 on 2025-08-29 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_groupmessageimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMemberRSVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('M', 'Maybe')], max_length=1)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.GroupMember')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.GroupSchedule')),
            ],
        ),
    ]
