# Generated by Django 2.2.7 on 2020-07-07 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ('groups', '0012_groupmessageimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMemberRSVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=None, max_length=36, unique=True)),
                ('canceled', models.NullBooleanField()),
                ('canceled_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='groups.GroupMember')),
            ],
        ),
    ]
