# Generated by Django 6.0.3 on 2026-03-23 18:30

from django.db import migrations, models

def create_dr_group_members(apps, schema_editor):
    GroupMember = apps.get_model('groups', 'GroupMember')
    DrGroupMember = apps.get_model('groups', 'DrGroupMember')
    
    for gm in GroupMember.objects.all():
        DrGroupMember.objects.create(
            dr_member=gm.user,
            group=gm.group,
            owner=gm.owner,
            is_admin=gm.admin,
            is_deleted=gm.is_deleted
        )

def reverse_dr_group_members(apps, schema_editor):
    DrGroupMember = apps.get_model('groups', 'DrGroupMember')
    DrGroupMember.objects.all().delete()

class Migration(migrations.Migration):
    
    dependencies = [
        ('groups', '0013_groupmemberrsvp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('dr_member', models.ForeignKey(on_delete=models.CASCADE, to='users.user')),
                ('group', models.ForeignKey(on_delete=models.CASCADE, to='groups.group')),
            ],
        ),
        migrations.RunPython(create_dr_group_members, reverse_code=reverse_dr_group_members),
    ]


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_groupmemberrsvp'),
    ]

    operations = [
    ]
