# Generated by Django 6.0.3 on 2026-03-23 19:43

from django.db import migrations


from django.db import migrations, models
import uuid
import django.db.models.deletion
import django.utils.timezone
import ckeditor.fields

class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0015_alter_group_options_alter_groupmember_options_and_more'),
    ]

    operations = [
        # Add UUID field for the new primary key
        migrations.AddField(
            model_name='group',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ), 
        # Make temp_id not null
        migrations.AlterField(
            model_name='group',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=False),
        ),
        
        # Add timestamps to Group
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Update the owner field with related_name
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='owned_groups', 
                to='users.user'
            ),
        ),
    ]
