# Generated by Django 4.2.20 on 2026-07-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0017_remove_group_temp_id_alter_group_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupschedule',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupschedule',
            name='schedule_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupschedule',
            name='venue_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupschedule',
            name='venue_map_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='groupschedule',
            name='venue_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
