# Generated by Django 4.2.20 on 2026-07-12 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0019_alter_groupmessage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='event_date',
        ),
    ]
