# Generated by Django 4.2.20 on 2026-07-17 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0021_groupevent_delete_groupschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupevent',
            options={'ordering': ['-event_time']},
        ),
        migrations.RemoveField(
            model_name='groupevent',
            name='rsvp_close',
        ),
        migrations.RemoveField(
            model_name='groupevent',
            name='rsvp_open',
        ),
    ]
